### ISSUE TITLE
RSS發送問題

### ISSUE THREAD

**Issue by Kayxue** [Gary50613/Taiwan_COVID-19_RSS#4]
JavaScript的Date所儲存的是一個數字，表示從格林威治標準時間1970-01-01 00:00:00到現在所經過的時間，單位為毫秒

所以這樣可能會造成衛福部剛發出的訊息在機器人收到後不會發出，因為這個迴圈
![image](https://user-images.githubusercontent.com/26020165/118935719-69fae400-b97e-11eb-8d56-c8e92581d2a9.png)

**Comment by kane50613** [comment]
現在應該修好了 在試試看吧
